export const START_LOADING = 'START_LOADING'
export const STOP_LOADING = 'STOP_LOADING'
export const SHOW_SNACKBAR = 'SHOW_SNACKBAR'
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR'

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR'
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR'

export const SAVE_USER = 'SAVE_USER'
export const USER_LOGOUT = 'USER_LOGOUT'
export const SET_ACTIVE = 'SET_ACTIVE'
export const UPDATE_AVATAR = 'UPDATE_AVATAR'
